apiVersion: v1
kind: Service
metadata:
  name: redmine-service
spec:
  type: NodePort
  selector:
    app: redmine-dev
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 3000
      nodePort: 30007
